/**:
  ros__parameters:

    drone_0:
      start_point_x: 0.0
      start_point_y: 0.0
      start_point_z: 0.5

# Mission scenario - toy3
scenario:
  mission:
    commands:
        - formation_type: "none"
          formation_scale: 0.0
          distance_threshold: 0.1
          waypoints:
            - [67.0, 5.0, 0.5]
