/**:
  ros__parameters:
    num_drones: 4

    formation_center_x: 0.0
    formation_center_y: 0.0
    formation_center_z: 0.0

    distance_threshold: 7.0

    enable_waypoint_markers: true
    enable_global_trajectory_pub: true

    # Drone hardware mapping (start_point defined in scenario files)
    drone_0:
      index: 0          # Internal agent index (0,1,2,3...) -> /agent0/target_position
      mavlink_id: 1     # External MAVLink ID (can be non-consecutive) -> /vehicle1/fmu/...

    drone_1:
      index: 1          # Internal: /agent1/...
      mavlink_id: 2     # External: /vehicle5/fmu/...

    drone_2:
      index: 2          # Internal: /agent2/...
      mavlink_id: 3     # External: /vehicle7/fmu/...

    drone_3:
      index: 3          # Internal: /agent3/...
      mavlink_id: 4     # External: /vehicle9/fmu/...

