/**:
  ros__parameters:
    # Number of Drones
    num_drones: 4
    
    use_initial_formation: true
    formation_center_x: -9.83
    formation_center_y: -67.0
    formation_center_z: 0.0

    formation_type: "line"
    formation_scale: 4.0
    distance_threshold: 4.0
    
    drone_0:
      drone_id: 0
      start_point_x: 0.00
      start_point_y: 0.00
      start_point_z: 0.00

    drone_1:
      drone_id: 1
      start_point_x: 0.24
      start_point_y: 1.99
      start_point_z: 0.00

    drone_2:
      drone_id: 2
      start_point_x: 0.49
      start_point_y: 3.97
      start_point_z: 0.00

    drone_3:
      drone_id: 3
      start_point_x: 0.73
      start_point_y: 5.96
      start_point_z: 0.00

