/**:
  ros__parameters:
    obstacles: [
      0.0,  15.0,  0.0,  # Left side of road
      3.0,  18.0,  0.0,  # Right side of road  
      1.2,  25.0,  0.0,  # On road center-left
      2.0,  30.0,  0.0,  # On road center-right
      1.8,  45.0,  0.0,  # Road center obstacle
      0.8,  60.0,  0.0   # Road left side
    ]