/**:
  ros__parameters:
    optimization/constrain_points_perPiece: 3  
    optimization/weight_obstacle: 50000.0  
    optimization/weight_swarm: 50000.0        
    optimization/weight_feasibility: 10000.0 
    optimization/weight_sqrvariance: 10000.0  
    optimization/weight_time: 80.0      
    optimization/weight_formation: 15000.0    
    optimization/obstacle_clearance: 0.5   
    optimization/swarm_clearance: 0.5 
    optimization/formation_type: 1   
    optimization/max_vel: 1.5        
    optimization/max_acc: 8.0 